// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyCE5dfuF7-6NwzBBW4-eeX-HylaaGikurE',
    appId: '1:900625754093:web:191acc2c469836e783e9e4',
    messagingSenderId: '900625754093',
    projectId: 'easy-shopping-5452e',
    authDomain: 'easy-shopping-5452e.firebaseapp.com',
    storageBucket: 'easy-shopping-5452e.appspot.com',
    measurementId: 'G-HSKLGE006R',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCjUjeV7EneDTeVJVE1Y1SsC_AbRnKN5Wg',
    appId: '1:900625754093:android:65f1659bc7ef937483e9e4',
    messagingSenderId: '900625754093',
    projectId: 'easy-shopping-5452e',
    storageBucket: 'easy-shopping-5452e.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyD4ENUhQiuknLmJl8FpoKIgFFhPjZiz3GI',
    appId: '1:900625754093:ios:22455e073ee12c5983e9e4',
    messagingSenderId: '900625754093',
    projectId: 'easy-shopping-5452e',
    storageBucket: 'easy-shopping-5452e.appspot.com',
    androidClientId:
        '900625754093-t4ibikqo1k01mf3pf750elnfar2o6ia4.apps.googleusercontent.com',
    iosClientId:
        '900625754093-et0hm78up00c3fl1lui2lm7mpc83eljb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomFirebaseApp',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyD4ENUhQiuknLmJl8FpoKIgFFhPjZiz3GI',
    appId: '1:900625754093:ios:103f56c0a3ae267d83e9e4',
    messagingSenderId: '900625754093',
    projectId: 'easy-shopping-5452e',
    storageBucket: 'easy-shopping-5452e.appspot.com',
    androidClientId:
        '900625754093-t4ibikqo1k01mf3pf750elnfar2o6ia4.apps.googleusercontent.com',
    iosClientId:
        '900625754093-kqc3ql7mt4dhvtssknv4is92bf16iijh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomFirebaseApp.RunnerTests',
  );
}
